// 本文件是十大排序算法的标准模板，使用了vector<int>作为容器，注释使用English(Generated by Github copilot),writen by 高能的核聚变 Github：https://github.com/QilongZhao-86
//请需要完整Data Structure and Algorithm Note(Markdown)请访问上面的地址中个人主页下的仓库。
//sort 算法需要重点考虑边界条件，比如空数组，单元素数组，有重复元素的数组等，并且需要考虑时间复杂度和空间复杂度。
#include <bits/stdc++.h>
using namespace std;
// Sorting an array by different functions
bool CheckAscending(vector<int>& arr, int start = 0, int end = -1) // checks if the array is sorted in ascending order
{
    if(end == -1)
    {
        end = arr.size() - 1;
    }
    if (start < 0 || end > arr.size() || start >= end) 
        return true;
    for (int i = start; i < end; i++)
    {
        if (arr[i] > arr[i + 1])
        {
            return false;
        }
    }
    return true;
}
void BubbleSort(vector<int>& arr) // sorts the array in ascending order using bubble sort algorithm
{
    // every time we will bubble up the largest element to the end of the array
    // we will do n-1 passes
    int n = arr.size();
    for (int i = 0; i < n; i++) 
    {
        for (int j = 0; j < n - i - 1; j++)
        {
            if (arr[j] > arr[j + 1])
            {
                swap(arr[j], arr[j + 1]); 
            }
        }
    }
    return;
}
void BubbleSortPart(vector<int>& arr, int start = 0, int end = -1) // sorts the array in ascending order using bubble sort algorithm for a part of the array
{
    // every time we will bubble up the largest element to the end of the array
    // we will do n-1 passes
    if(end == -1)
    {
        end = arr.size() - 1;
    }
    if(start < 0 || end >= arr.size() || start >= end)
        return;
    for (int i = start; i <= end; i++) 
    {
        for (int j = start; j <= end - (i - start) - 1; j++)
        {
            if (arr[j] > arr[j + 1])
            {
                swap(arr[j], arr[j + 1]); 
            }
        }
    }
    return;
}
void SelectionSort(vector<int>& arr) // sorts the array in ascending order using selection sort algorithm
{
    // every time we will select the minimum element from the unsorted array and swap it with the first element of the unsorted array
    // we will do n-1 passes
    int n = arr.size();
    int minIndex;
    for (int i = 0; i < n - 1; i++)
    {
        minIndex = i;
        for (int j = i + 1; j < n; j++)
        {
            if (arr[j] < arr[minIndex])
            {
                minIndex = j;
            }
        }
        swap(arr[i], arr[minIndex]);
    }
    return;
}
void SelectionSortPart(vector<int>& arr, int start = 0, int end = -1) // sorts the array in ascending order using selection sort algorithm for a part of the array
{
    if(end == -1)
    {
        end = arr.size() - 1;
    }
    if(start < 0 || end >= arr.size() || start >= end)
        return;
    // every time we will select the minimum element from the unsorted array and swap it with the first element of the unsorted array
    // we will do n-1 passes
    int minIndex;
    for (int i = start; i < end; i++)
    {
        minIndex = i;
        for (int j = i + 1; j <= end; j++)
        {
            if (arr[j] < arr[minIndex])
            {
                minIndex = j;
            }
        }
        swap(arr[i], arr[minIndex]);
    }
    return;
}
void InsertionSort(vector<int>& arr)//sorts the array in ascending order using insertion sort algorithm
{
    //we will take one element from the unsorted array and insert it into the sorted array at the correct position
    //we will do n-1 passes
    int n = arr.size();
    for(int i = 1; i < n; i++)
    {
        //Store current element as key
        int key = arr[i];
        //Find the correct position for key in the sorted part [0...i-1]
        int j = i - 1;
        //Move elements greater than key one position ahead
        while (j >= 0 && arr[j] > key)
        {
            arr[j + 1] = arr[j];
            j--;
        }
        //Place key at its correct position
        arr[j + 1] = key;
    }
    return; 
}
void InsertionSortPart(vector<int>& arr, int start = 0, int end = -1) //sorts the array in ascending order using insertion sort algorithm for a part of the array
{
    if(end == -1)
    {
        end = arr.size() - 1;
    }
    if(start < 0 || end >= arr.size() || start >= end)
        return;
    //we will take one element from the unsorted array and insert it into the sorted array at the correct position
    //we will do n-1 passes
    for(int i = start + 1; i <= end; i++)
    {
        //Store current element as key
        int key = arr[i];
        //Find the correct position for key in the sorted part [start...i-1]
        int j = i - 1;
        //Move elements greater than key one position ahead
        while (j >= start && arr[j] > key)
        {
            arr[j + 1] = arr[j];
            j--;
        }
        //Place key at its correct position
        arr[j + 1] = key;
    }
    return;
}
void MergeSort()
{

}
int main()
{

}